### ISSUE TITLE
Error after typing lspe -h

### ISSUE THREAD

**Issue by stereodruid** [littlstar/ls-psvr-encoder#8]
After installing the encoder with: npm install littlstar/ls-psvr-encoder -g

0           
   11       11    111010    011010      00      11011   111010      00      01 10           
   10       00      10        11        01      1100      10      00  00    1111           
   00       00      11        10        11      10110     11      10001     1001           
   0000     10      10        11      1011     010100     10       0100     11011           
   1110     10      00        01      0001      1101      10       0 11     10 11           

Outputting PSVR sideload video to /root/Videos//nan_80_sbs.mp4
Dependencies not satisfied. Exiting.

About to exit with code: 1

My OS is LinuxMint 18.
Node version is: v8.9.4

**Comment by randybruder** [comment]
Try re-running the
```bash
brew reinstall ffmpeg --with-fdk-aac --with-sdl2 --with-freetype --with-frei0r --with-libass --with-libvorbis --with-libvpx --with-opencore-amr --with-openjpeg --with-opus --with-theora --with-tools
```
command.

**Comment by stereodruid** [comment]
Working now. Thank  you for your help.
